version: '2'
services:
  baseimage:
    build: ./baseimage
    image: hyperledger/fabric-baseimage:latest

  membersrvc:
    image: ibmblockchain/fabric-membersrvc:x86_64-0.6.1-preview
    extends:
      file: membersrvc.yaml
      service: membersrvc

  vp:
    image: ibmblockchain/fabric-peer:x86_64-0.6.1-preview
    extends:
      file: peer-secure-base.yaml
      service: peer-secure-base
    volumes:       
      - /Users/rodneicouto/Dev/Workspace/les:/mnt/workspace
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=vp
      - CORE_SECURITY_ENROLLSECRET=f3489fy98ghf
    links:
      - membersrvc